TOPLEVEL_LANG = verilog
SIM = verilator

VERILOG_SOURCES = \
     ../gpu_pkg.sv\
     controller.sv 

TOPLEVEL = controller
MODULE = tb_controller

include $(shell cocotb-config --makefiles)/Makefile.sim