TOPLEVEL_LANG = verilog
SIM = verilator

VERILOG_SOURCES = \
     ../gpu_pkg.sv\
     writeback.sv 


TOPLEVEL = writeback
MODULE = tb_writeback 


include $(shell cocotb-config --makefiles)/Makefile.sim